```python
class Foo:
    def __enter__(self):
        '''
        with Foo 触发enter执行，返回值给f
        '''
        return 111

    def __exit__(self, exc_type, exc_val, exc_tb):
        '''
        运行结素触发这个方法。
        遇到错误也会触发这个方法。
        exc_type: 错误类型
        exc_vale: 错误值
        exc_tab: 错误跟踪
        return: 返回一个真，报错就会会被吸收。立刻退出with块，执行其他代码
        '''
        print('exc_type: ', exc_type)
        print('exc_val: ', exc_val)
        print('exc_tb: ', exc_tb)

        return True

with Foo() as f:
    print(f)
    raise TypeError('类型错误')
    print(111)
```